version: "3.8"

services:
  # === LARAVEL & NGINX ===
  laravel-app:
    build:
      context: ./henscare-iot
      dockerfile: Dockerfile
    container_name: henscare.iot
    restart: always
    volumes:
      - ./henscare-iot:/var/www/html
    expose:
      - 9000
    networks:
      app-network:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./henscare-iot:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      app-network:

  # === ELK STACK ===
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      app-network:

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.20
    container_name: logstash
    volumes:
      - ./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    networks:
      app-network:
        ipv4_address: 172.28.0.10

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.20
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      app-network:

  # === SPRING BOOT MICROSERVICES ===
  eureka-server:
    build: ./eureka-service
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      app-network:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://172.28.0.10:12201"

  api-gateway:
    build: ./api-gateway-service
    container_name: api-gateway-service
    ports:
      - "7000:7000"
    depends_on:
      - eureka-server
    networks:
      app-network:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://172.28.0.10:12201"

  dht-service:
    build: ./dht-service
    container_name: dht-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      app-network:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://172.28.0.10:12201"

  ultrasonik-service:
    build: ./ultrasonik-service
    container_name: ultrasonik-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      app-network:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://172.28.0.10:12201"

  rtc-service:
    build: ./rtc-service
    container_name: rtc-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      app-network:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://172.28.0.10:12201"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    networks:
      app-network:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://172.28.0.10:12201"

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
