version: "3.8"

services:
  laravel-app:
    build:
      context: ./henscare-iot
      dockerfile: Dockerfile
    container_name: henscare.iot
    restart: always
    volumes:
      - ./henscare-iot:/var/www/html
    expose:
      - 9000
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./henscare-iot:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - app-network

  # === SPRING BOOT MICROSERVICES ===
  eureka-server:
    build: ./eureka-service
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway-service
    container_name: api-gateway-service
    ports:
      - "7000:7000"
    depends_on:
      - eureka-server
    networks:
      - app-network

  dht-service:
    build: ./dht-service
    container_name: dht-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - app-network

  ultrasonik-service:
    build: ./ultrasonik-service
    container_name: ultrasonik-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - app-network

  rtc-service:
    build: ./rtc-service
    container_name: rtc-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8085:8085"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge